name: generate ascii art work

on:
  push

jobs:
  build_job_1:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install cowsay program
      run: sudo apt-get install cowsay

    - name: excecute cowsay cmd
      run: cowsay -f dragon "Run for cover, i'am a dragon" >> dragon.txt

    - name: upload dragon to artifact
      uses: actions/upload-artifact@v4
      with:
        name: dragon-text
        path: dragon.txt
    
  test_job_2:
    needs: build_job_1
    runs-on: ubuntu-latest

    steps:
    - name: download artifact
      uses: actions/download-artifact@v4
      with:
        name: dragon-text
        
    - name: test file exists
      run: grep -i "dragon" dragon.txt
    
  deploy_job_3:
    needs: [build_job_1,test_job_2]
    runs-on: ubuntu-latest

    steps:
    - name: download artifact
      uses: actions/download-artifact@v4
      with:
        name: dragon-text

    - name: read file
      run: cat dragon.txt

    - name: deploy
      run: echo "Deploying ...."
