name: matrix configuration

on:
  push:
  workflow_dispatch: 

jobs:
    # deploy-on-ubuntu:
    #   runs-on: ubuntu-latest
    #   steps:
    #   - name: echo docker details
    #     run: docker info

    #   - name: rum images
    #     run: docker run hello-world

    # deploy-on-windows:
    #   runs-on: windows-latest
    #   steps:
    #   - name: echo docker details
    #     run: docker info
      
    #   - name: run images
    #     run: docker run hello-world
    deploy:
      runs-on: ${{matrix.os}}
      strategy:
        fail-fast: false
        max-parallel: 2
        matrix:
          os: [ubuntu-latest,windows-latest]
          images: [hello-world,alpine]
          exclude:
            - images: alpine
              os: windows-latest
          include:
            - images: amd64/alpine
              os: windows-latest
      steps:
      - name: echo docker details
        run: docker info

      - name: rum images on ${{ matrix.os }}
        run: docker run ${{ matrix.images }}
          