name: exploring workflow filters
on:
  workflow_dispatch: 
  push:
    # branches-ignore:
    #   - feature/*
    #   - test/**
    branches:
      - main
      - '!feature/*'

  pull_request:
    branches:
      - main
    paths-ignore:
      - README.md
    types:
      - opened
      - synchronize
      - reopened
      - closed

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - run: echo this workflow/job/step is executed for event type - ${{ github.event_name }}  